export const fakeReviewsList = [
  {
    id: 1,
    review:
      "This product completely changed my life! lorewwdiwboiwnxoinwiwixwnoixnww xwixwixnw wnxownxownoxwn xwnxownxowoxnwo wxnownxownxon I've never experienced such quality and reliability in any other product. Highly recommend!",
    rating: 5,
    user: "HappyCustomer123",
    img: "https://randomuser.me/api/portraits/men/19.jpg",
    postedOn: "Google",
    time: "2 month ago",
  },
  {
    id: 2,
    review:
      "Absolutely fantastic! I bought this on a whim completely changed my life! lorewwdiwboiwnxoinwiwixwnoixnww xwixwixnw wnxownxownoxwn xwnxownxowoxnwo wxnownxownxon  and it exceeded all my expectations. Five stars!",
    rating: 5,
    user: "ThrilledBuyer456",
    img: "https://randomuser.me/api/portraits/men/80.jpg",
    postedOn: "Google",
    time: "2 month ago",
  },
  {
    id: 3,
    review: "Worst purchase ever. Broke within a week. completely changed my life! lorewwdiwboiwnxoinwiwixwnoixnww xwixwixnw wnxownxownoxwn xwnxownxowoxnwo wxnownxownxon completely changed my life! lorewwdiwboiwnxoinwiwixwnoixnww xwixwixnw wnxownxownoxwn xwnxownxowoxnwo wxnownxownxon completely changed my life! lorewwdiwboiwnxoinwiwixwnoixnww xwixwixnw wnxownxownoxwn xwnxownxowoxnwo wxnownxownxon completely changed my life! lorewwdiwboiwnxoinwiwixwnoixnww xwixwixnw wnxownxownoxwn xwnxownxowoxnwo wxnownxownxon  Don't waste your money!",
    rating: 1,
    user: "DisappointedShopper789",
    img: "https://randomuser.me/api/portraits/med/men/12.jpg",
    postedOn: "Google",
    time: "2 month ago",
  },
  {
    id: 4,
    review:
      "Incredible customer service! They went above and beyond to make sure I was satisfied with my purchase.",
    rating: 5,
    user: "GreatServiceFanatic",
    img: "https://randomuser.me/api/portraits/med/men/16.jpg",
    postedOn: "Google",
    time: "2 month ago",
  },
  {
    id: 5,
    review: "Meh. It's okay, I guess. Wouldn't buy again.",
    rating: 2,
    user: "NeutralUser101",
    img: "https://randomuser.me/api/portraits/med/men/23.jpg",
    postedOn: "Google",
    time: "2 month ago",
  },
  {
    id: 6,
    review:
      "I've been using this for months and it's still as good as new. Definitely worth every penny.",
    rating: 4,
    user: "LongTermUserXYZ",
    img: "https://randomuser.me/api/portraits/med/men/22.jpg",
    postedOn: "Google",
    time: "2 month ago",
  },
  {
    id: 7,
    review: "Great value for the price! I'm amazed at how well it performs.",
    rating: 5,
    user: "BudgetBuyer789",
    img: "https://randomuser.me/api/portraits/med/men/26.jpg",
    postedOn: "Google",
    time: "2 month ago",
  },
  {
    id: 8,
    review:
      "Terrible quality. Fell apart after the first use. Do not recommend.",
    rating: 1,
    user: "UnsatisfiedCustomer999",
    img: "https://randomuser.me/api/portraits/med/men/29.jpg",
    postedOn: "Google",
    time: "2 month ago",
  },
  {
    id: 9,
    review: "Super fast shipping! Got it sooner than expected.",
    rating: 4,
    user: "SpeedyDeliveryGuy",
    img: "https://randomuser.me/api/portraits/med/men/32.jpg",
    postedOn: "Google",
    time: "2 month ago",
  },
  {
    id: 10,
    review: "Exactly what I needed. Perfect fit and works like a charm.",
    rating: 5,
    user: "PrecisionSeeker777",
    img: "https://randomuser.me/api/portraits/med/men/42.jpg",
    postedOn: "Google",
    time: "2 month ago",
  },
];
