// export const REACT_APP_WEB = "fgstore.web";
// export const REACT_APP_WEB = "fgstore.pro";  // procatalog website
// export const REACT_APP_WEB = "fgstore.plw";   //similing rock PLW
// export const REACT_APP_WEB = "fgstore.mapp";   //similing rock mobile app
// export const REACT_APP_WEB = "diamondtine.web";
// export const REACT_APP_WEB = "hoq.web";
// export const REACT_APP_WEB = "malakan.web";
// export const REACT_APP_WEB = "rpjewel.web";
// export const REACT_APP_WEB = "stamford.web";
// export const REACT_APP_WEB = "lovein.web";
// export const REACT_APP_WEB = "ornaz.web";
// export const REACT_APP_WEB = "demostore";
// export const REACT_APP_WEB = "forevery.web";    // Forevery.web | Foreveryd.optigoapps.com  | world.forevery.one
export const REACT_APP_WEB = "elvee.web";   // elvee.in
// export const REACT_APP_WEB = "fgstorepro.mapp";   // procatalog mobile app 
